var searchData=
[
  ['base64_20url_20decoding_0',['base64 url decoding',['..//Users/shelat/Projects/longfellow-zk/lib/circuits/base64/README.md#autotoc_md0',1,'']]],
  ['base64decoder_1',['Base64Decoder',['../classproofs_1_1_base64_decoder.html',1,'proofs']]],
  ['benchmarks_2',['Running benchmarks',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['binaryfieldtypetag_3',['BinaryFieldTypeTag',['../structproofs_1_1_binary_field_type_tag.html',1,'proofs']]],
  ['bindings_4',['bindings',['../structproofs_1_1_prover_layers_1_1bindings.html',1,'proofs::ProverLayers']]],
  ['bit_5fplucker_5fpoint_5',['bit_plucker_point',['../structproofs_1_1bit__plucker__point.html',1,'proofs']]],
  ['bitadderaux_6',['BitAdderAux',['../classproofs_1_1_bit_adder_aux.html',1,'proofs']]],
  ['bitadderaux_3c_20logic_2c_20n_2c_20false_20_3e_7',['BitAdderAux&lt; Logic, N, false &gt;',['../classproofs_1_1_bit_adder_aux_3_01_logic_00_01_n_00_01false_01_4.html',1,'proofs']]],
  ['bitadderaux_3c_20logic_2c_20n_2c_20logic_3a_3afield_3a_3akcharacteristictwo_20_3e_8',['BitAdderAux&lt; Logic, N, Logic::Field::kCharacteristicTwo &gt;',['../classproofs_1_1_bit_adder_aux.html',1,'proofs']]],
  ['bitadderaux_3c_20logic_2c_20n_2c_20true_20_3e_9',['BitAdderAux&lt; Logic, N, true &gt;',['../classproofs_1_1_bit_adder_aux_3_01_logic_00_01_n_00_01true_01_4.html',1,'proofs']]],
  ['bitplucker_10',['BitPlucker',['../classproofs_1_1_bit_plucker.html',1,'proofs']]],
  ['bitplucker_3c_20logiccircuit_2c_20kmacpluckerbits_20_3e_11',['BitPlucker&lt; LogicCircuit, kMACPluckerBits &gt;',['../classproofs_1_1_bit_plucker.html',1,'proofs']]],
  ['bitpluckerencoder_12',['BitPluckerEncoder',['../classproofs_1_1_bit_plucker_encoder.html',1,'proofs']]],
  ['bitpluckerencoder_3c_20field_2c_202_20_3e_13',['BitPluckerEncoder&lt; Field, 2 &gt;',['../classproofs_1_1_bit_plucker_encoder.html',1,'proofs']]],
  ['bitvec_14',['bitvec',['../classproofs_1_1_logic_1_1bitvec.html',1,'proofs::Logic']]],
  ['bitvec_3c_201_20_3e_15',['bitvec&lt; 1 &gt;',['../classproofs_1_1_logic_1_1bitvec.html',1,'proofs::Logic']]],
  ['bitvec_3c_20128_20_3e_16',['bitvec&lt; 128 &gt;',['../classproofs_1_1_logic_1_1bitvec.html',1,'proofs::Logic']]],
  ['bitvec_3c_20129_20_3e_17',['bitvec&lt; 129 &gt;',['../classproofs_1_1_logic_1_1bitvec.html',1,'proofs::Logic']]],
  ['bitvec_3c_2016_20_3e_18',['bitvec&lt; 16 &gt;',['../classproofs_1_1_logic_1_1bitvec.html',1,'proofs::Logic']]],
  ['bitvec_3c_20256_20_3e_19',['bitvec&lt; 256 &gt;',['../classproofs_1_1_logic_1_1bitvec.html',1,'proofs::Logic']]],
  ['bitvec_3c_2032_20_3e_20',['bitvec&lt; 32 &gt;',['../classproofs_1_1_logic_1_1bitvec.html',1,'proofs::Logic']]],
  ['bitvec_3c_204_20_3e_21',['bitvec&lt; 4 &gt;',['../classproofs_1_1_logic_1_1bitvec.html',1,'proofs::Logic']]],
  ['bitvec_3c_2064_20_3e_22',['bitvec&lt; 64 &gt;',['../classproofs_1_1_logic_1_1bitvec.html',1,'proofs::Logic']]],
  ['bitvec_3c_208_20_3e_23',['bitvec&lt; 8 &gt;',['../classproofs_1_1_logic_1_1bitvec.html',1,'proofs::Logic']]],
  ['bitw_24',['BitW',['../structproofs_1_1_logic_1_1_bit_w.html',1,'proofs::Logic']]],
  ['blas_25',['Blas',['../classproofs_1_1_blas.html',1,'proofs']]],
  ['blockwitness_26',['BlockWitness',['../structproofs_1_1_flat_s_h_a256_circuit_1_1_block_witness.html',1,'proofs::FlatSHA256Circuit&lt; Logic, BitPlucker &gt;::BlockWitness'],['../structproofs_1_1_flat_s_h_a256_witness_1_1_block_witness.html',1,'proofs::FlatSHA256Witness::BlockWitness']]],
  ['bogorng_27',['Bogorng',['../classproofs_1_1_bogorng.html',1,'proofs']]],
  ['build_28',['Instructions to build',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['building_20manually_29',['Building manually',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['but_20the_20gates_20have_20changed_30',['If the inputs and witnesses are the same, but the gates have changed',['..//Users/shelat/Projects/longfellow-zk/lib/circuits/mdoc/README.md#autotoc_md7',1,'']]]
];
