var searchData=
[
  ['cbor_0',['Cbor',['../classproofs_1_1_cbor.html',1,'proofs']]],
  ['cbor_3c_20logiccircuit_2c_20kmdoc1cborindexbits_20_3e_1',['Cbor&lt; LogicCircuit, kMdoc1CborIndexBits &gt;',['../classproofs_1_1_cbor.html',1,'proofs']]],
  ['cbor_3c_20logicf_20_3e_2',['Cbor&lt; LogicF &gt;',['../classproofs_1_1_cbor.html',1,'proofs']]],
  ['cbor_5fplucker_5fpoint_3',['cbor_plucker_point',['../structproofs_1_1cbor__plucker__point.html',1,'proofs']]],
  ['cborbytedecoder_4',['CborByteDecoder',['../classproofs_1_1_cbor_byte_decoder.html',1,'proofs']]],
  ['cborconstants_5',['CborConstants',['../structproofs_1_1_cbor_constants.html',1,'proofs']]],
  ['cbordoc_6',['CborDoc',['../classproofs_1_1_cbor_doc.html',1,'proofs']]],
  ['cborindex_7',['CborIndex',['../structproofs_1_1_cbor_index.html',1,'proofs::CborIndex'],['../structproofs_1_1mdoc__1f_1_1_cbor_index.html',1,'proofs::mdoc_1f&lt; LogicCircuit, Field, EC, kNumAttr &gt;::CborIndex'],['../structproofs_1_1_mdoc_hash_1_1_cbor_index.html',1,'proofs::MdocHash&lt; LogicCircuit, Field &gt;::CborIndex']]],
  ['cborplucker_8',['CborPlucker',['../classproofs_1_1_cbor_plucker.html',1,'proofs']]],
  ['cborplucker_3c_20proofs_3a_3alogic_2c_20kncounters_20_3e_9',['CborPlucker&lt; proofs::Logic, kNCounters &gt;',['../classproofs_1_1_cbor_plucker.html',1,'proofs']]],
  ['cborplucker_3c_20proofs_3a_3alogiccircuit_2c_20kncounters_20_3e_10',['CborPlucker&lt; proofs::LogicCircuit, kNCounters &gt;',['../classproofs_1_1_cbor_plucker.html',1,'proofs']]],
  ['cbortesting_11',['CborTesting',['../classproofs_1_1_cbor_testing.html',1,'proofs']]],
  ['cborwitness_12',['CborWitness',['../classproofs_1_1_cbor_witness.html',1,'proofs']]],
  ['celt_13',['CElt',['../structproofs_1_1_fp_generic_1_1_c_elt.html',1,'proofs::FpGeneric&lt; W64, optimized_mul, OPS &gt;::CElt'],['../structproofs_1_1_g_f2__128_1_1_c_elt.html',1,'proofs::GF2_128&lt; subfield_log_bits &gt;::CElt']]],
  ['celtw_14',['CEltW',['../structproofs_1_1_counter_aux_3_01_logic___00_01false_01_4_1_1_c_elt_w.html',1,'proofs::CounterAux&lt; Logic_, false &gt;::CEltW'],['../structproofs_1_1_counter_aux_3_01_logic___00_01true_01_4_1_1_c_elt_w.html',1,'proofs::CounterAux&lt; Logic_, true &gt;::CEltW']]],
  ['challenge_15',['Challenge',['../structproofs_1_1_challenge.html',1,'proofs']]],
  ['changed_16',['changed',['..//Users/shelat/Projects/longfellow-zk/lib/circuits/mdoc/README.md#autotoc_md7',1,'If the inputs and witnesses are the same, but the gates have changed'],['..//Users/shelat/Projects/longfellow-zk/lib/circuits/mdoc/README.md#autotoc_md8',1,'If the inputs/witnesses have changed']]],
  ['circuit_17',['Circuit',['../structproofs_1_1_circuit.html',1,'proofs']]],
  ['circuit_20files_18',['Circuit files',['..//Users/shelat/Projects/longfellow-zk/lib/circuits/mdoc/circuits/README.md#autotoc_md2',1,'']]],
  ['circuit_3c_20proofs_3a_3agf2_5f128_20_3e_19',['Circuit&lt; proofs::GF2_128 &gt;',['../structproofs_1_1_circuit.html',1,'proofs']]],
  ['circuitrep_20',['CircuitRep',['../classproofs_1_1_circuit_rep.html',1,'proofs']]],
  ['claims_21',['claims',['../structproofs_1_1_verifier_layers_1_1claims.html',1,'proofs::VerifierLayers']]],
  ['compilerbackend_22',['CompilerBackend',['../classproofs_1_1_compiler_backend.html',1,'proofs']]],
  ['corner_23',['corner',['../structproofs_1_1_quad_1_1corner.html',1,'proofs::Quad&lt; Field &gt;::corner'],['../structproofs_1_1_sparse_1_1corner.html',1,'proofs::Sparse&lt; Field &gt;::corner']]],
  ['corresponding_20to_20version_202_24',['(Removed) Hashes from 2025-05-15 corresponding to version 2',['..//Users/shelat/Projects/longfellow-zk/lib/circuits/mdoc/circuits/README.md#autotoc_md5',1,'']]],
  ['counteraux_25',['CounterAux',['../classproofs_1_1_counter_aux.html',1,'proofs']]],
  ['counteraux_3c_20logic_2c_20logic_3a_3afield_3a_3akcharacteristictwo_20_3e_26',['CounterAux&lt; Logic, Logic::Field::kCharacteristicTwo &gt;',['../classproofs_1_1_counter_aux.html',1,'proofs']]],
  ['counteraux_3c_20logic_5f_2c_20false_20_3e_27',['CounterAux&lt; Logic_, false &gt;',['../classproofs_1_1_counter_aux_3_01_logic___00_01false_01_4.html',1,'proofs']]],
  ['counteraux_3c_20logic_5f_2c_20true_20_3e_28',['CounterAux&lt; Logic_, true &gt;',['../classproofs_1_1_counter_aux_3_01_logic___00_01true_01_4.html',1,'proofs']]],
  ['cpoly_29',['CPoly',['../structproofs_1_1_layer_proof.html',1,'proofs']]]
];
