FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-24.04

RUN apt update && export DEBIAN_FRONTEND=noninteractive \
	&& apt install -y clang cmake git g++ libssl-dev libzstd-dev libgtest-dev libbenchmark-dev zlib1g-dev
